#### Add the Project Root to `sys.path`

This allows the notebook to import modules from the `src` directory by adding the project's root folder to Python's module search path.

In [2]:
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent))

#### Importing Modules from `src` directory

In [3]:
from src.data_ingestion import convert_yaml_to_match_csv, convert_yaml_to_ball_csv

#### Converting the Folder of .yaml files to Match-by-Match CSV and Ball-By-Ball CSV

The datasets are stored in `root\data\interim` directory.

In [4]:
YAML_FOLDER = Path("../data/raw")
OUTPUT_FOLDER = Path("../data/interim")

match_csv = convert_yaml_to_match_csv(YAML_FOLDER, OUTPUT_FOLDER / "match_by_match.csv")
ball_csv = convert_yaml_to_ball_csv(YAML_FOLDER, OUTPUT_FOLDER / "ball_by_ball.csv")

100%|██████████| 1244/1244 [03:53<00:00,  5.32it/s]

Match-by-Match CSV saved at ..\data\interim\match_by_match.csv

100%|██████████| 1244/1244 [03:44<00:00,  5.55it/s]

Ball-by-Ball CSV saved at ..\data\interim\ball_by_ball.csv

In [17]:
print(f"Shape of Match-by-Match CSV is {match_csv.shape}")
match_csv.head()

Shape of Match-by-Match CSV is (1243, 13)

,match_id,date,venue,team1,team2,toss_winner,toss_decision,winner,result,team1_score,team2_score,team1_players,team2_players
0,1082591,2017-04-05,"Rajiv Gandhi International Stadium, Uppal",Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,won by 35 runs,207,172,"DA Warner, S Dhawan, MC Henriques, Yuvraj Sing...","CH Gayle, Mandeep Singh, TM Head, KM Jadhav, S..."
1,1082592,2017-04-06,Maharashtra Cricket Association Stadium,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,won by 7 wickets,184,187,"AM Rahane, MA Agarwal, SPD Smith, BA Stokes, M...","PA Patel, JC Buttler, RG Sharma, N Rana, AT Ra..."
2,1082593,2017-04-07,Saurashtra Cricket Association Stadium,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,won by 10 wickets,183,184,"JJ Roy, BB McCullum, SK Raina, AJ Finch, KD Ka...","G Gambhir, CA Lynn, RV Uthappa, MK Pandey, YK ..."
3,1082594,2017-04-08,Holkar Cricket Stadium,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,won by 6 wickets,163,164,"HM Amla, M Vohra, WP Saha, AR Patel, GJ Maxwel...","AM Rahane, MA Agarwal, SPD Smith, BA Stokes, M..."
4,1082595,2017-04-08,M.Chinnaswamy Stadium,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,won by 15 runs,157,142,"CH Gayle, SR Watson, Mandeep Singh, KM Jadhav,...","AP Tare, SW Billings, KK Nair, SV Samson, RR P..."

In [16]:
print(f"Shape of Match-by-Match CSV is {ball_csv.shape}")
ball_csv.head()

Shape of Match-by-Match CSV is (295732, 11)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,bowler,non_striker,runs_batsman,runs_total
0,1082591,1st innings,Sunrisers Hyderabad,Royal Challengers Bangalore,0,1,DA Warner,TS Mills,S Dhawan,0,0
1,1082591,1st innings,Sunrisers Hyderabad,Royal Challengers Bangalore,0,2,DA Warner,TS Mills,S Dhawan,0,0
2,1082591,1st innings,Sunrisers Hyderabad,Royal Challengers Bangalore,0,3,DA Warner,TS Mills,S Dhawan,4,4
3,1082591,1st innings,Sunrisers Hyderabad,Royal Challengers Bangalore,0,4,DA Warner,TS Mills,S Dhawan,0,0
4,1082591,1st innings,Sunrisers Hyderabad,Royal Challengers Bangalore,0,5,DA Warner,TS Mills,S Dhawan,0,2